### ISSUE TITLE
Trigger doorbell remotly

### ISSUE THREAD

**Issue by mbrevda** [mnpg/Reolink_api_documentations#2]
I'm looking for a way to emulate pressing the doorbell button remotely. I realize this isn't a support channel, but was hoping perhaps someone was aware of a command or some other mechanism (433 perhaps?).

**Comment by mnpg** [comment]
hi @mbrevda, 
first i ain't got a doorbell and i don't know how the two parts communicate (wifi, 433Mhz??).
All i know is, the API commands of the Doorbell are to control the selection of the reply messages, the sound of the doorbell itself (not the chime) or the light of the doorbell itself.

**Comment by mbrevda** [comment]
> I don't know how the two parts communicate

I'd be happy just emulating a button push and let it do the work. When pressing the button., the unit sends out a 433Mhz signal to the chime, and also sends a "visitor" notification via it's regular channels (push, callbacks, etc).

Poking around the firmware, there are some strings related to "doorbell test" but not sure how one would go about triggering those.

Its such a nice device, almost wish it was open source so that we could help with the development!

Thanks anyway!

**Comment by mnpg** [comment]
Thanks you @mbrevda for your return. 
I don't know how these parts are communicated. I know that the floodlight communicate in WIFI but not the doorbell. Now we know! Can you, or have you, activate the chime through a 433Mhz signal? did it's work? 
Many thanks for your answers
Regards

**Comment by mbrevda** [comment]
> Can you, or have you, activate the chime through a 433Mhz signal?

I didn't, but I saw another [posting how](https://www.reddit.com/r/reolinkcam/comments/zs7538/comment/j1afscc/?utm_source=reddit&utm_medium=web2x&context=3) (also [here](https://github.com/merbanan/rtl_433/issues/2277)). Was hoping not to have to invest in a transmitter though, especially seeing how I essentially have one

**Comment by mnpg** [comment]
OK. Thanks @mbrevda for your answer and links. It will be helpful for the developers.
